[global]
repo1-path=/var/lib/pgbackrest/repo1
repo1-type=posix
repo1-retention-full=7
repo1-retention-full-type=count
repo1-retention-archive-type=full
repo1-cipher-type=aes-256-cbc
repo2-path=/var/lib/pgbackrest/repo2
repo2-type=posix
repo2-retention-full=4
repo2-retention-full-type=count
repo2-retention-archive-type=full
repo2-cipher-type=aes-256-cbc
start-fast=y
log-level-console=info
log-level-file=detail
log-path=/var/log/pgbackrest
lock-path=/tmp/pgbackrest
spool-path=/var/spool/pgbackrest
process-max=2

[assistant]
pg1-path=/var/lib/postgresql/data
pg1-user=assistant
pg1-database=assistant
