"""Pure calendar occurrence expansion for scheduled tasks."""

from __future__ import annotations

from dataclasses import dataclass, replace
from datetime import UTC, date, datetime, time, timedelta
from zoneinfo import ZoneInfo

from croniter import croniter

MAX_OCCURRENCES_PER_TASK = 100


@dataclass(frozen=True, slots=True)
class CalendarTask:
    """Scheduled task data required to build a user calendar view."""

    id: int
    kind: str
    title: str
    payload: str
    cron_expr: str | None
    next_run_at: datetime
    status: str


@dataclass(frozen=True, slots=True)
class CalendarOccurrence:
    """One local occurrence exposed by the calendar API."""

    id: int
    kind: str
    text: str
    time_local: str
    occurs_at: str
    recurring: bool
    repeat_human: str | None
    status: str
    truncated: bool = False

    @property
    def local_date(self) -> str:
        """Return the ISO local date used as the API day key."""

        return self.occurs_at[:10]


def expand_occurrences(
    tasks: list[CalendarTask],
    from_date: date,
    to_date: date,
    timezone: ZoneInfo,
    *,
    cap: int = MAX_OCCURRENCES_PER_TASK,
) -> list[CalendarOccurrence]:
    """Expand one-off and cron tasks across an inclusive local-date range."""

    if to_date < from_date:
        raise ValueError("calendar range end precedes start")
    if cap < 1:
        raise ValueError("calendar occurrence cap must be positive")

    range_start = datetime.combine(from_date, time.min, tzinfo=timezone)
    range_end = datetime.combine(to_date + timedelta(days=1), time.min, tzinfo=timezone)
    occurrences: list[CalendarOccurrence] = []
    for task in tasks:
        if task.status == "cancelled":
            continue
        if task.cron_expr is None:
            local = _aware(task.next_run_at).astimezone(timezone)
            if range_start <= local < range_end:
                occurrences.append(_occurrence(task, local, recurring=False))
            continue

        task_occurrences: list[CalendarOccurrence] = []
        iterator = croniter(task.cron_expr, range_start - timedelta(microseconds=1))
        while len(task_occurrences) <= cap:
            local = iterator.get_next(datetime)
            if local.tzinfo is None:
                local = local.replace(tzinfo=timezone)
            else:
                local = local.astimezone(timezone)
            if local >= range_end:
                break
            if local >= range_start:
                task_occurrences.append(_occurrence(task, local, recurring=True))
        if len(task_occurrences) > cap:
            task_occurrences = [
                replace(occurrence, truncated=True) for occurrence in task_occurrences[:cap]
            ]
        occurrences.extend(task_occurrences)

    return sorted(occurrences, key=lambda item: (item.occurs_at, item.id, item.kind))


def repeat_human(cron_expr: str) -> str:
    """Describe cron patterns generated by reminder creation in Russian."""

    fields = cron_expr.split()
    if len(fields) != 5:
        return "по расписанию"
    minute, hour, day_of_month, month, day_of_week = fields
    if not (_number_in_range(minute, 0, 59) and _number_in_range(hour, 0, 23)):
        return "по расписанию"
    clock = f"{int(hour):02d}:{int(minute):02d}"
    if day_of_month == "*" and month == "*" and day_of_week == "*":
        return f"каждый день в {clock}"
    weekdays = {
        "0": "воскресеньям",
        "1": "понедельникам",
        "2": "вторникам",
        "3": "средам",
        "4": "четвергам",
        "5": "пятницам",
        "6": "субботам",
    }
    if day_of_month == "*" and month == "*" and day_of_week in weekdays:
        return f"по {weekdays[day_of_week]} в {clock}"
    if _number_in_range(day_of_month, 1, 31) and month == "*" and day_of_week == "*":
        return f"{int(day_of_month)}-го числа в {clock}"  # noqa: RUF001
    return "по расписанию"


def _occurrence(
    task: CalendarTask,
    local: datetime,
    *,
    recurring: bool,
) -> CalendarOccurrence:
    return CalendarOccurrence(
        id=task.id,
        kind=task.kind,
        text=task.payload if task.kind == "reminder" else task.title,
        time_local=local.strftime("%H:%M"),
        occurs_at=local.isoformat(),
        recurring=recurring,
        repeat_human=repeat_human(task.cron_expr) if recurring and task.cron_expr else None,
        status=task.status,
    )


def _aware(value: datetime) -> datetime:
    if value.tzinfo is None:
        return value.replace(tzinfo=UTC)
    return value


def _number_in_range(value: str, lower: int, upper: int) -> bool:
    return value.isdigit() and lower <= int(value) <= upper
