---
galaxy_info:
  author: Project maintainers
  description: Base host configuration and hardening role.
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - noble
  galaxy_tags: []
